{
 "title": "Test-Direct-Queries",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Cluster Physical Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n date_trunc('day', to_timestamp(reporting.storage_usage_stats.timestamp_usecs / 1000000)) AS \"time\",\n avg(reporting.storage_usage_stats.physical_size_bytes / 1024 / 1024 / 1024) AS physical_size\nFROM reporting.storage_usage_stats\nGROUP BY reporting.storage_usage_stats.timestamp_usecs\nORDER BY reporting.storage_usage_stats.timestamp_usecs"
    }
   ]
  },
  {
   "title": "Cluster Logical Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n date_trunc('hour', to_timestamp(reporting.storage_usage_stats.timestamp_usecs / 1000000)) AS \"time\",\n avg(reporting.storage_usage_stats.logical_size_bytes / 1024 / 1024 / 1024) AS logical_size\nFROM reporting.storage_usage_stats\nGROUP BY reporting.storage_usage_stats.timestamp_usecs\nORDER BY reporting.storage_usage_stats.timestamp_usecs\n"
    }
   ]
  },
  {
   "title": "Daily AVG Dedupe Rate - Backups",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('hour', to_timestamp(reporting.storage_usage_stats.timestamp_usecs / 1000000)) AS \"time\",\n  avg(reporting.storage_usage_stats.data_in_bytes / 1024 / 1024::bigint / NULLIF(reporting.storage_usage_stats.data_written_bytes / 1024 / 1024::bigint, 0)) AS dedupe\nFROM reporting.storage_usage_stats\nwhere reporting.storage_usage_stats.data_in_bytes is not null and reporting.storage_usage_stats.entity_type = 1\nGROUP BY reporting.storage_usage_stats.timestamp_usecs\nORDER BY reporting.storage_usage_stats.timestamp_usecs"
    }
   ]
  },
  {
   "title": "Daily AVG Dedupe Rate - Views",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('hour', to_timestamp(reporting.storage_usage_stats.timestamp_usecs / 1000000)) AS \"time\",\n  avg(reporting.storage_usage_stats.data_in_bytes / 1024 / 1024::bigint / NULLIF(reporting.storage_usage_stats.data_written_bytes / 1024 / 1024::bigint, 0)) AS dedupe\nFROM reporting.storage_usage_stats\nwhere reporting.storage_usage_stats.data_in_bytes is not null and reporting.storage_usage_stats.entity_type = 3\nGROUP BY reporting.storage_usage_stats.timestamp_usecs\nORDER BY reporting.storage_usage_stats.timestamp_usecs"
    }
   ]
  },
  {
   "title": "Daily AVG Dedupe Rate - Replication",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('hour', to_timestamp(reporting.storage_usage_stats.timestamp_usecs / 1000000)) AS \"time\",\n  avg(reporting.storage_usage_stats.data_in_bytes / 1024 / 1024::bigint / NULLIF(reporting.storage_usage_stats.data_written_bytes / 1024 / 1024::bigint, 0)) AS dedupe\nFROM reporting.storage_usage_stats\nwhere reporting.storage_usage_stats.data_in_bytes is not null and reporting.storage_usage_stats.entity_type = 2\nGROUP BY reporting.storage_usage_stats.timestamp_usecs\nORDER BY reporting.storage_usage_stats.timestamp_usecs"
    }
   ]
  },
  {
   "title": "AVG Daily Projection Job Error Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\n  date_trunc('hour'::text, to_timestamp((reporting.protection_job_runs.start_time_usecs / 1000000)::double precision)) AS \"time\",\n  count(reporting.protection_job_runs.status) AS \"status_count\"\n\nFROM reporting.protection_job_runs\n\nWHERE\n  reporting.protection_job_runs.status = 6\n  \nGROUP BY reporting.protection_job_runs.start_time_usecs\nORDER BY reporting.protection_job_runs.start_time_usecs \n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "select \n\ndate_trunc('day', to_timestamp(reporting.protection_job_storage_stats.timestamp_usecs / 1000000)) AS \"time\",\nreporting.protection_job_storage_stats.job_id,\nreporting.protection_job_storage_stats.data_in_bytes / 1024 / 1024 / 1024 as \"data_in_bytes\",\nreporting.protection_job_storage_stats.data_written_bytes / 1024 / 1024 / 1024 as \"data_written_bytes\"\n\nfrom reporting.protection_job_storage_stats\nwhere reporting.protection_job_storage_stats.data_in_bytes is not null\nGROUP BY \nreporting.protection_job_storage_stats.job_id, \nreporting.protection_job_storage_stats.timestamp_usecs,\nreporting.protection_job_storage_stats.data_in_bytes,\nreporting.protection_job_storage_stats.data_written_bytes\nORDER BY\nreporting.protection_job_storage_stats.data_in_bytes DESC\nlimit 10"
    }
   ]
  }
 ]
}